### ISSUE TITLE
Edytujmy okręgi.txt

### ISSUE THREAD

**Issue by jakub-** [PartiaRazem/mapy#3]
@waranzzakomody, dzięki za Twoje zmiany. :)

`okręgi.geojson` jest generowany z `okręgi.txt`, więc to ten drugi powinniśmy zmieniać, wraz z samym skryptem generującym (`generate.rb`), gdy to konieczne.

**Comment by jakub-** [comment]
Zmieniłem backend na Binga, dzięki czemu pojawiły się polskie znaki w nazwach miejscowości.

**Comment by drogus** [comment]
@jakub- wrzuciem PR #4, który sam będzie generował okregi.geojson używając Travis CI. Trzeba by tylko ustawić to na Travisie, możemy o tym pogadać wieczorem.

**Comment by drogus** [comment]
Jeszcze tylko dodam, że chodzi o to, żeby tego pliku w ogóle nie było w repo, żeby nie mylić nikogo.

**Comment by jakub-** [comment]
OK, teraz już wszystko powinno być jasne, skoro okręgi.geojson zniknęły.
